plugins {
    id 'fabric-loom' version '1.17.12'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation files("libs/fabric-api-0.157.0+26.2.jar")
}

processResources {
    inputs.property "version", project.version
    filteringCharset = "UTF-8"
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    withSourcesJar()
}

jar {
    archiveBaseName = "SimolClient-V1"
    archiveVersion = ""
    archiveClassifier = ""
}

tasks.named("remapJar") {
    archiveBaseName = "SimolClient-V1"
    archiveVersion = ""
    archiveClassifier = ""
}
